### ISSUE TITLE
Big picture question

### ISSUE THREAD

**Issue by ericsink** [microsoft/node-api-dotnet#113]
(This "issue" would go in Discussions instead of Issues.)

Interesting project here!

Can you say anything about the future goals of this project or how "official" it is with respect to Microsoft?

It looks like this started out as maybe a side project of a few Microsoft employees, and then last month it moved under the Microsoft organization.  Does that mean this is now part of the work of a product team, in DevDiv, perhaps?

Just curious.

FWIW, I've been working on some JS/dotnet interop stuff myself, although my work is currently in a private repo because it is very exploratory.  There are some significant differences between what I'm doing and what's happening here, but there are some commonalities as well, so I find this repo quite interesting.

Thanks!

**Comment by jasongin** [comment]
The best I can say at this point that it is "semi-official", with possibility for it becoming more real and fully supported in the near future.

> It looks like this started out as maybe a side project of a few Microsoft employees, and then last month it moved under the Microsoft organization. 

That's accurate. @vmoroz and I have been collaborating on it for several months as an experimental side project, and more recently we have gotten some minor sponsorship from his team, and approval to move the project into the Microsoft org.

> Does that mean this is now part of the work of a product team, in DevDiv, perhaps?

It is heading in that direction, but not decided yet. Some internal teams have started experimenting with it, and we have started discussions with other teams about how the project might align with related efforts.

We chose to make the project public while still in early stages primarily so that we can get feedback from developers about how they might like to use it. And since it integrates other open-source projects (.NET and Node.js / Node API) it just seemed natural to be open from the start. We can accept contributions, if others are interested.

**Comment by ericsink** [comment]
Thanks for the reply!

**Comment by ericsink** [comment]
Just a little FYI deliberately hidden here in a comment on a closed issue:

In a blog entry today about my own .NET/TypeScript interop efforts, I mentioned your project:

https://ericsink.com/native_aot/typescript.html

You folks seem quite focused and heads-down, but if at any point you want to discuss common ground or share ideas, let me know.

Cheers!
