### ISSUE TITLE
.NET HTTP3 interop scenarios

### ISSUE THREAD

**Issue by ladeak** [microsoft/node-api-dotnet#160]
I have been experimenting with this library. I have a tool that is written in .NET 8, AOT compiled, and I try to use the C# API from a VS Code Extension (electron) app. 
When the tool uses HTTP2 to make HTTP requests with HttpClient in the .NET assembly, the request is sent, and a response is received.

However, when using HTTP3 in the .NET assembly (which uses msquic on Windows), I got an empty response. I would like to better understand what could be the reason behind it: likely that it cannot access the msquic lib.
So far, I tested that the native AOT package when simply used as an executable it can make the HTTP3 requests, and responses are received.

Could you point me to the right direction to continue my investigation on this?

**Comment by jasongin** [comment]
> it cannot access the msquic lib

I am aware there is currently a problem when an assembly depends on a native library that it expects to load from the same directory. So far I haven't found a good general solution. If that is the issue here, you should be able to work around the problem by explicitly loading the msquic native library with `dotnet.load()`. See [the WPF example](https://github.com/microsoft/node-api-dotnet/blob/0c245a80504ef38cc541ab9c6cf76d0b14e813e4/examples/wpf/example.js#L22), which explicitly loads a couple native libraries that the WPF assemblies depend on.

**Comment by ladeak** [comment]
I think that is going to be the issue. I will check the workaround, thank you for the suggestion.

**Comment by ladeak** [comment]
I will close this issue, as I think this is now an issue to be opened in .NET 8. See my comment in https://github.com/dotnet/runtime/issues/73290
