### ISSUE TITLE
Processing of overloaded methods causes 'An item with the same key has already been added' error. 

### ISSUE THREAD

**Issue by alexeybut** [microsoft/node-api-dotnet#199]
Generating NodeJS module with AOT of classes with overloaded methods raises the exception:
```
CSC : error NAPI1001: ArgumentException : An item with the same key has already been added. Key: ConsoleApp1_Class2_DoSom ething   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)   at Sy stem.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)   at Microsoft.JavaScript.NodeApi.Generator.ModuleGener ator.ExportMethod(SourceBuilder& s, IMethodSymbol method, String exportName)   at Microsoft.JavaScript.NodeApi.Generator. ModuleGenerator.ExportMembers(SourceBuilder& s, ITypeSymbol type)   at Microsoft.JavaScript.NodeApi.Generator.ModuleGener ator.ExportType(SourceBuilder& s, ITypeSymbol type, String exportName)   at Microsoft.JavaScript.NodeApi.Generator.Module Generator.ExportModule(SourceBuilder& s, ITypeSymbol moduleType, IEnumerable`1 exportItems)   at Microsoft.JavaScript.Nod eApi.Generator.ModuleGenerator.GenerateModuleInitializer(ISymbol moduleInitializer, IEnumerable`1 exportItems)   at Micro soft.JavaScript.NodeApi.Generator.ModuleGenerator.Execute(GeneratorExecutionContext context)
```
Problem class sample:
```
    [Microsoft.JavaScript.NodeApi.JSExport]
    public class Class2 
    {
        public void DoSomething(int c) { }
        public void DoSomething(char c) { }
    }
```
I suppose an incremental renaming can be used (ex. DoSomething1) or a detailed error like 'Overloaded methods aren't supported.' can be thrown.

**Comment by alexeybut** [comment]
Using _[Microsoft.JavaScript.NodeApi.JSExport("DoSomething2")]_ for renaming doesn't help.

**Comment by jasongin** [comment]
Thanks for the bug report. Overloads are not supported in that scenario, but it definitely should report a better error message.

The current design of `[JSExport]` assumes that since you are writing the code (not merely consuming someone else's API), then you can design it to fit JavaScript patterns. And the JS runtime does not have overloads. Instead, it uses optional or variable-type parameters. (While TypeScript allows for declaration of "overloads", they are just multiple type definitions for the same JS method.)

There is [limited](https://github.com/microsoft/node-api-dotnet/issues/134) support for overloads with dynamic invocation of .NET APIs from JS (which I need to document better), but currently not for explicit exports using `[JSExport]`. That capability could be extended to explicit exports, with a little more work.
