### ISSUE TITLE
node-api-dotnet-generator is not able to find DLLs in Linux

### ISSUE THREAD

**Issue by james-hu** [microsoft/node-api-dotnet#200]
In Linux environment, node-api-dotnet-generator does not seem to be able to find DLLs unless specified via command line arguments (`--reference`).

I looked into the source code, it seems the problem is in `Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86)` which is not able to find the installation directory in Linux.

Below is my workaround:
```
#!/bin/bash

localDllDir=MySolution/MyProject/bin/net6.0
aspNetCoreVer=`dotnet --list-runtimes | grep 'AspNetCore.App 6' | grep -oP '(?<= ).*(?= )'`
aspNetCoreDllDir=`dotnet --list-runtimes | grep 'AspNetCore.App 6' | grep -oP '(?<=\[).*(?=\])'`/$aspNetCoreVer

argsFile=node-api-dotnet-generator.args.txt

rm -rf $argsFile

((ls $localDllDir/*.dll | grep -v MyProject.dll) && ls $aspNetCoreDllDir/*.dll) | xargs -I{} echo -n " -r {} " >> $argsFile

mkdir -p src/generated
npx node-api-dotnet-generator --assembly $localDllDir/MyProject.dll --typedefs src/generated/my-project.d.ts @node-api-dotnet-generator.args.txt
```

It would be good if the tool is able to find default directories in Linux and then automatically use DLLs in those directories as references.

**Comment by jasongin** [comment]
Thanks for the issue report.

We haven't used or tested the `node-api-dotnet-generator` tool very much since I added MSBuild integration, in which MSBuild resolves the paths to all the referenced DLLs before passing them to the generator explicitly. Is there a reason why you don't want to use MSBuild to generate the typedefs? See [this doc](https://github.com/microsoft/node-api-dotnet/blob/main/Docs/node-module.md) for instructions on setting it up.

Regardless, I think we still should support the standalone tool, so I'll keep this bug open.

**Comment by james-hu** [comment]
I haven't tried the MSBuild approach. I think I will try it when the other blocking issue is resolved. Thanks.
I am currently blocked by the compatibility issue (GLIBC / libc.so.6 version and Node.js version)

**Comment by james-hu** [comment]
Just to update, Microsoft.JavaScript.NodeApi.Generator works as expected without additional configuration on Linux.

**Comment by jasongin** [comment]
Referenced assemblies that are part of .NET (specifically part of the `Microsoft.NETCore.App` pack) are located automatically on Linux. For other packs like ASP.NET you may need to add `--pack Microsoft.AspNetCore.App`. That might be all that was missing here.

Assemblies in any other location cannot be found automatically because the tool does not have any context from MSBuild beyond what is passed in on the command-line, so that is by design.

> it seems the problem is in `Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86)` which is not able to find the installation directory in Linux.

That code is conditional on targeting .NET Framework 4.x, which is only supported on Windows. Targeting other .NET versions does not reference the ProgramFiles folder; it uses `System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory()` instead.

If this is still a problem, feel free to re-open with more details including the command-line (or response file) passed to the `node-api-dotnet-generator` tool, and any console output.
