### ISSUE TITLE
Update platform initialization for newest libnode revisions

### ISSUE THREAD

**Issue by samardzicneo** [microsoft/node-api-dotnet#218]
The current code used to initialize Nodejs (`CreatePlatform` and `CreateEnvironment`) is using an older version of the libnode embedding API.
The new version removes the `execArgs` parameter for `CreatePlatform` and adds a new parameter to `CreateEnvironment` that lets you specify the platform version (I'm not sure what this does exactly, in my testing it kinda did nothing).

Are there plans to support this new API? How would a backwards-compatible variant of this even look, considering that the delegate pointers for both of these have strongly-typed parameters?

**Comment by jasongin** [comment]
Yes, I've been planning for a while to update that, but haven't prioritized it since the PR has been in limbo. But @vmoroz is planning to help with that PR soon, so updating this project be a good validation of the revised embedding API before getting that PR merged.

> How would a backwards-compatible variant of this even look, considering that the delegate pointers for both of these have strongly-typed parameters?

I'm not sure I understand this question... but since there is no need to support older revisions of the PR, I don't think there's a back-compat concern?

**Comment by jasongin** [comment]
>  I'm not sure if you guys want to keep compatibility with Node DLLs that were built with the old API.

No, I don't think anyone has any expectation of such compatibility.

**Comment by jasongin** [comment]
We didn't have an issue tracking this, so I'll put this one on the project plan.
