### ISSUE TITLE
How to use the compiled source library with a Unity project？

### ISSUE THREAD

**Issue by 526677804** [microsoft/node-api-dotnet#315]
1.NuGet
![NuGet](https://github.com/microsoft/node-api-dotnet/assets/44428270/e8c79003-427a-40fb-bc22-e77898225adc)

2.Assembly
![Assembly](https://github.com/microsoft/node-api-dotnet/assets/44428270/3c0ccdaf-fffd-4313-b95c-c9d2752eac4d)

I tried to modify some source code and recompile it, but after referencing it as an assembly, I could successfully compile the dll, but could not generate the .d.ts, .cjs, .mjs intermediate files.

Do I need to set any project properties?

**Comment by jasongin** [comment]
It is difficult for me to understand from screenshots what you are trying to do. It is not clear what is the relationship between the 2 projects / assemblies you're working with, and where the code and references are.

If you have a project with a reference to the `Microsoft.JavaScript.NodeApi.Generator` nuget package, and that project contains C# source files with `[JSExport]` attributes, then it should generate the `.d.ts` when you build the project.

**Comment by 526677804** [comment]
Thank you very much for your answer,  I will try to describe the problem again.

1.I have a project with a reference to the Microsoft.JavaScript.NodeApi.Generator nuget package，and that project contains C# source files with [JSExport] attributes, then it should generate the .d.ts when you build the project.（Screenshot 1. NuGet）

2.I have another project with a reference to the Microsoft.JavaScript.NodeApi.Generator from nuget local package location as an assembly, and that project contains C# source files with [JSExport] attributes, successfully compile the dll, but could not generate the .d.ts, .cjs, .mjs intermediate files.（Screenshot 2. Assembly）

3.Both projects use the same C# code

question：Why do I get different results when referencing a local dll as an assembly and directly referencing a NuGet package?

**Comment by jasongin** [comment]
> Why do I get different results when referencing a local dll as an assembly and directly referencing a NuGet package?

Because the nuget package includes a `Microsoft.JavaScript.NodeApi.Generator.targets` file which is automatically imported into the project, which hooks the TS generator into the build process.

**Comment by 526677804** [comment]
![image](https://github.com/microsoft/node-api-dotnet/assets/44428270/7187801e-be7d-45d3-9a33-c35bde468255)

I looked at the contents of the `Microsoft.JavaScript.NodeApi.Generator.targets` and found that it used a lot of different versions of things, and there was also an automatic import of the `.props` files and other `.targets` files.For example, `Microsoft.CodeAnalysis.Analyzers.targets` and `Microsoft.CodeAnalysis.Analyzers.props`, etc.

By using NuGet reference library in C# project, this usage is smooth.

However, in actual scenarios, NuGet may not be used. For example, if you want to use this library to communicate with other applications developed in JavaScript in a Unity C# project, you cannot use NuGet to do some automatic processing. I have made some attempts by referring to projects that use NuGet, but I have not been successful because the scope of the content involved cannot be determined. 

This is why I raised this issue, because I want to use the library without NuGet, but the [node-api-dotnet](https://github.com/microsoft/node-api-dotnet) has not released a Release package. Is there a way to obtain the release package and extract the library or configuration file suitable for the development environment of my  Unity C# project(C# version: .NET Framework 4.7.1 or .NET Standard 2.0)? Or do you have experience using this library in Unity?

**Comment by jasongin** [comment]
I do not have experience with Unity, so it is very surprising to me that it does not support regular NuGet package references.

`Microsoft.JavaScript.NodeApi.Generator` is both a C# source generator and a separate tool that generates TypeScript type definitions. Most of the targets file is about setting up the typedefs generation.

The C# source generator [generates the marshalling code](https://github.com/microsoft/node-api-dotnet/pull/318/files?short_path=bbaa6d1#diff-bbaa6d1e1d212ce9fc486a684bafd09fd125ef27c81715e9504d3f6818b5d430) for items in your project that are exported to JavaScript with `[JSExport]`. To add the source generator to your Unity project I think you can use the steps described at https://docs.unity3d.com/6000.0/Documentation/Manual/install-existing-analyzer.html. The "Analyzers" props/targets are related to setting up the source generator, so if you use the steps in the linked doc I don't think you need those files.

Generating type definitions is not absolutely necessary, since you can still write JavaScript code without the type definitions. But it is strongly recommended for a better development experience. It is going to be difficult to generate type definitions without the MSBuild targets file, since that takes care of locating all the referenced assemblies which are needed by the generator. You might actually be able to use `Microsoft.JavaScript.NodeApi.Generator.targets` with the Unity project, maybe with some small modifications. I don't think it depends on any other automatically-imported props or targets files.

**Comment by jasongin** [comment]
I'm going to go ahead and close this issue because there is currently no plan to build any special accommodations for Unity, if it doesn't support NuGet packages. If others are interested in this, feel free to discuss here or open a new issue.
