### ISSUE TITLE
Unwrapping structs of unknown types

### ISSUE THREAD

**Issue by camnewnham** [microsoft/node-api-dotnet#346]
If I create a dotnet object from the JS side and pass it to dotnet, I can `RemoveWrap` to get a dotnet `Object`.  Subsequently type switches or similar can be used to determine how to respond to the object.

However with a struct, I'm unable to unwrap it. Since I don't know the type in advance, I can't use `JSMarshaller.FromJS<T>`. I understand that struct does not inherit from object, but is it be possible to unwrap this into a Nullable or some other type of object wrapper?

**Comment by jasongin** [comment]
Since [structs are marshalled by value](https://microsoft.github.io/node-api-dotnet/reference/structs-tuples.html#structs), there is no "wrapped" .NET object behind a JS struct object. The object has to be marshalled from JS to .NET (which marshals each property of the struct), and that requires knowing the type.

There is a way to find the type though: the JS struct object's `constructor` is a JS class object which wraps the .NET `Type` object:

```C#
JSValue structValue = ...
Type structType = ((JSObject)structValue["constructor"]).Unwrap<Type>();
object structObj = typeof(JSMarshaller)
    .GetMethod(nameof(JSMarshaller.FromJS))!.MakeGenericMethod(structType)
    .Invoke(marshaller, new object[] { structValue });
```

I admit that is ugly - it could be simplified with a better API.

**Comment by camnewnham** [comment]
Thanks @jasongin, that's just what I needed! :)

**Comment by jasongin** [comment]
In #354 I am adding non-generic `FromJS()` and `ToJS()` methods.

**Comment by jasongin** [comment]
Closing this issue since the question was answered and the API was improved.
