### ISSUE TITLE
Eliminate JSValueScope object allocation on every call

### ISSUE THREAD

**Issue by jasongin** [microsoft/node-api-dotnet#57]
`JSValueScope` is the only heap allocation that is required on every call from JS to .NET. We should investigate eliminating that allocation, at least in the majority of calls.

A simple solution could be to save the last-used `JSValueScope` instance in a static variable when returning from a call, then re-use it on the next call, with a new handle. (But also allow for nested calls.)

**Comment by vmoroz** [comment]
The main reason we have `JSValueScope` allocated on the heap is to provide safe access to `napi_value` pointers.
We must know the exact time when the `napi_value` becomes invalid.
Otherwise using an invalid `napi_value` will cause application crashes.
Even worse, previous `napi_value` is deleted and we have a new `napi_value` with the same address, but different value.

There are different ways to implement this safety control:
- Keep a list of all known `napi_value` and invalidate them on scope closure. Such approach would require us to know addresses of all `JSValue` that wrap `napi_value`. The only way to make it safe is to change `JSValue` from `struct` to `class`. It essentially will require a memory allocation per each `JSValue`, but we can avoid allocation per `JSValueScope` in simple cases. It doesn't sound as a good trade off.
- Convert `JSValue` to `ref struct` and prohibit it being used outside of call stack. E.g. it will be not allowed to be part of a collection. It is possible to do, and it will be safe, but it becomes difficult to use `JSValue` in many scenarios.
- The current approach allocates one object per each scope regardless of how many `napi_value` are created. The important parts are:
  - `JSValueScope` is `IDisposable` so that `JSValue` can check the `IsDisposed` status to see that `napi_value` is not valid anymore.
  - `JSValueScope` must be allocated on the heap. It must be alive even after the scope is closed. Any `JSValue` that points to `JSValueScope` after the scope closure must keep a valid reference to know that it has an invalid `napi_value`.

It is not possible to keep `JSValueScope` as a static variable and to reuse it because it is bound to the stack scope and must not bounce to `false` after the `IsDisposed` is set to `true`.
We could implement a custom "resurrection" mechanism after the `JSValueScope` is not used anymore, but it doesn't make much sense: in .Net the allocation is cheap, but GC is expensive. The "resurrection" mechanism doesn't avoid GC but makes it is even more complex GC as it will involve the Finalizer queue.

The only solution that I see so far is to add a new `JSValueRef` type which is a `ref struct`. Use it in most cases.
In cases when it is difficult to use, we can get the current `JSValue` and allocate the `JSValueContext` on-demand.
At the first glance, it looks rather complex, but it could gain us perf improvements.
I can experiment with it to see how far we can go with it.

**Comment by jasongin** [comment]
> The "resurrection" mechanism doesn't avoid GC but makes it is even more complex GC as it will involve the Finalizer queue.

I'm not following that. It doesn't need to be anything complex, since saving only a single instance will be enough to avoid the great majority of allocations. [Here is a commit](https://github.com/microsoft/node-api-dotnet/commit/0e81d71ad56ea1daba7501b3bedf2eaeab18ea37) that implements what I was thinking of. In the `complex_types` test case, it reduces object allocations by **104**. When I get a chance later I'll check whether it has a measurable impact on the one perf benchmark we have. (Maybe it won't; I know the GC is highly optimized for dealing with small short-lived objects.)

I agree that "resurrecting" an object that was previously disposed seems a little dubious. But it might work out fine.

**Comment by vmoroz** [comment]
> > The "resurrection" mechanism doesn't avoid GC but makes it is even more complex GC as it will involve the Finalizer queue.
> 
> I'm not following that. It doesn't need to be anything complex, since saving only a single instance will be enough to avoid the great majority of allocations. [Here is a commit](https://github.com/microsoft/node-api-dotnet/commit/0e81d71ad56ea1daba7501b3bedf2eaeab18ea37) that implements what I was thinking of. In the `complex_types` test case, it reduces object allocations by **104**. When I get a chance later I'll check whether it has a measurable impact on the one perf benchmark we have. (Maybe it won't; I know the GC is highly optimized for dealing with small short-lived objects.)

The code in this commit is exactly what I was trying to caution about. It breaks the `JSValue` safety.
If we have a `JSValue` that references this `JSValueScope` and the `JSValueScope` is disposed, then there is no way that the `JSValue` can check that the wrapped `napi_value` is valid. This is because the `JSValueScope` can be reused and its status bounces back as non-disposed. It means that now the `JSValue` is allowed to use an invalid `napi_value` and get all the issues outlined above. 

The only safe way to "resurrect" `JSValueScope` is after it is started to get finalized. That means that there are no references to the object anymore. See the [MSDN article](https://learn.microsoft.com/en-us/archive/msdn-magazine/2000/november/garbage-collection-automatic-memory-management-in-the-microsoft-net-framework) where they talk about Resurrection.
```C#
   protected override void Finalize() {
        Application.ObjHolder = this; 
        GC.ReRegisterForFinalize(this);
    }
```
Unfortunately, the article is missing the full code - a link to the code is broken.
I saw a good example before in Jeffrey Richter's book "CLR via C#", but I could not find it in the 4th edition of the book.
Though, in 4th edition there is a class `GCNotification` that has a good outline of what needs to happen in the Finalizer for the proper resurrection. In addition to the code above, it must check for `!AppDomain.CurrentDomain.IsFinalizingForUnload() && !Environment.HasShutdownStarted`.

**Comment by jasongin** [comment]
> then there is no way that the `JSValue` can check that the wrapped `napi_value` is valid

Yes I see your point now. I know you covered that in the earlier reply too, but somehow I overlooked it.

I'll still collect some performance data with that unsafe optimization, just to help evaluate whether this is an area even worth putting effort into optimizing. But if it is then I get we'd need to use a different approach.

**Comment by jasongin** [comment]
Closing this as won't fix. @vmoroz and I have both investigated this and have not found a safe way to eliminate this allocation. And it doesn't seem to have much impact on performance.
